[nirvana]
auditors = ["Anchor core developers", "Solana Labs core developers"]
name = "Nirvana"
description = "Nirvana is a twin system of algorithmic wealth & ultra low-risk stablecoin on the Solana network.  It produces the ANA token: an algorithmic metastable token that serves as a store of wealth.  And it produces the NIRV token: a decentralized superstable store of value."
website = "https://nirvana.finance"
risksURL = "https://docs.nirvana.finance/risks"
iconURL = "https://nirvana.finance/Favicon.svg"

[uxd]
auditors = ["Bramah Systems", "Soteria"]
name = "UXD"
description = "UXD Protocol is an algorithmic stablecoin that is fully backed by a delta-neutral position using derivatives."
website = "https://uxd.fi/"
risksURL = "https://docs.uxd.fi/uxdprotocol/overview/risks"
iconURL = "https://uxd.fi/apple-touch-icon.png"

[calcifer]
auditors = []
name = "Calcifer"
description = "Calcifer Finance is a self repaying loan suite, using a brand new synthetic asset, calUSD. The platform creates advances on your yield farming via calUSD that represents a claim on any underlying collateral in Calcifer Finance."
website = "https://calcifer.fi/"
risksURL = "https://calcifer-finance.gitbook.io/calcifer-finance/calusd"
iconURL = "https://calcifer.fi/experiment.gif"

[fabric]
auditors = []
name = "Fabric"
website = "https://fsynth.io"
description = "Fabric's core feature is a protocol for issuing and trading synthetic assets on Solana. A synthetic (or synth) is an SPL token that tracks an external asset with the supply controlled by the protocol."
risksURL = "https://docs.fsynth.io/synthetics-protocol"
iconURL = "https://uploads-ssl.webflow.com/60b35c8cd73f399dc4a8d8b9/60b370df8e7b7a8633e75b16_FABLOGO_TRANS192.png"

[hedge]
auditors = ["Kudelski", "Soteria", "Ottersec"]
name = "Hedge"
website = "https://hedge.so"
description = "Hedge is a protocol that enables the minting of USH, a stablecoin soft-pegged to the US dollar. USH is minted on flexible terms and gives users instant access to the USH ecosystem."
risksURL = "https://docs.hedge.so/protocol-overview/faq"
iconURL = "https://www.hedge.so/_next/static/media/hedge-on-dark.c20a90d6.svg"

[blazestake]
auditors = ["Quantstamp", "Neodyme", "Kudelski"]
name = "BlazeStake"
website = "https://stake.solblaze.org"
description = "BlazeStake is a non-custodial liquid staking protocol that helps decentralize the Solana network while providing more consistent staking rewards. The protocol stakes SOL across many validators and provides a more liquid bSOL token to users to represent staked SOL. BlazeStake also offers additional features including airdrops for extra rewards and a treasury for supporting Solana ecosystem projects."
risksURL = "https://stake-docs.solblaze.org"
iconURL = "https://stake.solblaze.org/assets/icon.png"
sourceURL = "https://stake-docs.solblaze.org/developers/open-source-code"

[coin98]
# auditor source: https://blog.coin98.com/introducing-cusd/
auditors = ["\"Highly trusted auditors\""]
name = "Coin98"
website = "https://coin98.com/dollar"
description = "CUSD is designed to be the bloodline of the Coin98 Ecosystem, bringing a seamless unified cross-chain liquidity flow to the existing/upcoming infrastructures."
risksURL = "https://blog.coin98.com/introducing-cusd/"
iconURL = "https://coin98.com/static/media/cusdBall.12b6d308.svg"
